name: 'Notification action'
description: 'Notification reusable action'
author: 'Gutenberg Technology'


inputs:
  platform:
    description: 'Platform'
    required: false
  env:
    description: 'Environment'
    required: false
  service:
    description: 'Service'
    required: false
  version:
    description: 'Version'
    required: false
  github-repository-owner:
    description: 'GitHub repository owner'
    required: false
  datadog-enabled:
    description: 'Datadog enabled'
    required: true
    default: 'false'
  datadog-api-key:
    description: 'Datadog api key'
    required: false
    default: "YOUR_DATADOG_API_KEY"
  datadog-source-type-name:
    description: 'Datadog source type name'
    required: false
    default: 'github'
  slack-enabled:
    description: 'Slack enabled'
    required: true
    default: 'false'
  slack-webhook-url:
    description: 'Slack webhook url'
    required: false
  slack-channel:
    description: 'Slack channel'
    required: false
  slack-username:
    description: 'Slack user'
    required: false
  github-last-job-result:
    description: 'Slack color'
    required: false
  slack-icon:
    description: 'Slack icon'
    required: false
  slack-title:
    description: 'Slack title'
    required: false
  slack-message:
    description: 'Slack message'
    required: false
  slack-footer:
    description: 'Slack footer'
    required: false
    default: 'Gutenberg Technology'
  slack-markdown:
    description: 'Slackify markdown'
    required: false
    default: 'false'
  
runs:
  using: 'composite'
  steps:
    - name: Slack - Send Notification
      if: ${{ inputs.slack-enabled == 'true' }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.slack-webhook-url }}
        SLACK_CHANNEL: it_script
        SLACK_USERNAME: ${{ inputs.slack-username }}
        SLACK_COLOR: ${{ inputs.slack-color }}
        SLACK_ICON: ${{ inputs.slack-icon }}
        SLACK_MESSAGE: ${{ inputs.slack-message }}
        SLACK_TITLE: ${{ inputs.slack-title }}
        SLACK_FOOTER: ${{ inputs.slack-footer }}
        SLACKIFY_MARKDOWN: ${{ inputs.slack-markdown }}

    - name: Datadog - Send Event
      if: ${{ inputs.datadog-enabled == 'true' }}
      uses: Gutenberg-Technology/datadog-action@main
      with:
        api-key: ${{ inputs.datadog-api-key }}
        events: |
          - title: "[${{ inputs.env }}] ${{ inputs.service }} @ ${{ inputs.version }} is deployed"
            text: "Successfully deployed ${{ inputs.service }} @ ${{ inputs.version }} in ${{ inputs.platform }}-${{ inputs.env }}"
            alert_type: ${{ inputs.github-last-job-result }}
            host: "GitHub/${{ inputs.github-repository-owner }}"
            version: ${{ inputs.version }}
            platform: ${{ inputs.platform }}
            environment: ${{ inputs.env }}
            env: ${{ inputs.env }}
            service: ${{ inputs.service }}
            source: ${{ inputs.datadog-source-type-name }}
            tags:
              - "platform:${{ inputs.platform }}"
              - "version:${{ inputs.version }}"
              - "service:${{ inputs.service }}"
              - "environment:${{ inputs.env }}"
              - "env:${{ inputs.env }}"
              - source: ${{ inputs.datadog-source-type-name }}

        

