name: 'Notification action'
description: 'Notification reusable action'
author: 'Gutenberg Technology'


inputs:
  datadog-event:
    description: 'Datadog event'
    required: false
  slack-webhook-url:
    description: 'Slack webhook url'
    required: false
  slack-channel:
    description: 'Slack channel'
    required: false
  slack-username:
    description: 'Slack user'
    required: false
  slack-color:
    description: 'Slack color'
    required: false
  slack-icon:
    description: 'Slack icon'
    required: false
  slack-title:
    description: 'Slack title'
    required: false
  slack-message:
    description: 'Slack message'
    required: false
  
runs:
  using: 'composite'
  steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.slack-webhook-url }}
        SLACK_CHANNEL: it_script
        SLACK_USERNAME: ${{ inputs.slack-username }}
        SLACK_COLOR: ${{ inputs.slack-color }}
        SLACK_ICON: ${{ inputs.slack-icon }}
        SLACK_MESSAGE: ${{ inputs.slack-message }}
        SLACK_TITLE: ${{ inputs.slack-title }}

        

